language: minimal
dist: trusty
sudo: false
addons:
  apt:
    update: true
    packages:
    - gconf-service
    - lib32gcc1
    - lib32stdc++6
    - libasound2
    - libc6
    - libc6-i386
    - libcairo2
    - libcap2
    - libcups2
    - libdbus-1-3
    - libexpat1
    - libfontconfig1
    - libfreetype6
    - libgcc1
    - libgconf-2-4
    - libgdk-pixbuf2.0-0
    - libgl1-mesa-glx
    - libglib2.0-0
    - libglu1-mesa
    - libgtk2.0-0
    - libnspr4
    - libnss3
    - libpango1.0-0
    - libstdc++6
    - libx11-6
    - libxcomposite1
    - libxcursor1
    - libxdamage1
    - libxext6
    - libxfixes3
    - libxi6
    - libxrandr2
    - libxrender1
    - libxtst6
    - zlib1g
    - debconf
    - npm
    - libsoup2.4
    - libarchive-dev
before_install:
  - wget https://beta.unity3d.com/download/cc814e4d942d/UnitySetup-2017.4.9f1
  - chmod +x UnitySetup-2017.4.9f1
  - yes|./UnitySetup-2017.4.9f1 --unattended --install-location ./unity
  - UNITY3D=./unity/Editor/Unity make
